### ISSUE TITLE
Repository not added after confirming

### ISSUE THREAD

**Issue by jasonw4331** [poggit/poggit#62]
I previously attempted to add an empty repository to poggit and in the process, added a .poggit.yml file to the repository. After poggit recognised the repo as empty and removed it, I added my plugin files and attempted to re-add it back to poggit. I unchecked the create .poggit.yml box and clicked confirm. The repository still wasn't added even though there are the plugin's files in the repository and a .poggit.yml
![](http://imgur.com/2W0MNVu.png)

**Comment by Awzaw** [comment]
Try adding the project to poggit.yml, it was made 17 hours ago and is currently set to projects: []

**Comment by jasonw4331** [comment]
It added a random 0
![](http://imgur.com/NVyzW6N.png)

**Comment by Awzaw** [comment]
poggit.yml should be like this, at the most basic:

```
---
branches: master
projects:
  GlowstoneCircleWorld:
    path: ""
    model: default
...
```
