### ISSUE TITLE
Ignore files when building

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#81]
Currently, the files that get included in a build only include resources/, src/ and plugin.yml as in the default project builder, as well as a stub file (only one file) if specified in .poggit.yml.

This issue proposes the addition of extra files to include/exclude using the .poggit.yml, or a .poggitignore file. 

For example, in .poggit.yml:

```yaml
projects:
  $ProjectName:
    path: $ProjectPath
    excludes:
      - **.png
    includes:
      - stub/**
```

Or a .poggitignore file, using the (probably) same syntax as .gitignore: http://stackoverflow.com/a/20151790/3990767
